name: restfoodblindbox
description: "RFBB Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  badges: ^3.1.2
  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  firebase_messaging: ^15.0.1
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23

flutter_native_splash:
  color: "#f6f2e8"  # 背景顏色 (溫暖的米白色)
  image: assets/icon/icon.png # 中央的 Logo
  android: true
  ios: true