// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqvF7S3kPbM-F55T1_4ZZso-IE6kbGDpg',
    appId: '1:990427757093:android:35b5f1cdc6b4207a6b9dcc',
    messagingSenderId: '990427757093',
    projectId: 'restfoodblindbox',
    storageBucket: 'restfoodblindbox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4g9CA7Pc5ceKdxtsSkHOp_LzHMkd8o_4',
    appId: '1:990427757093:ios:7dfad37ac682f14a6b9dcc',
    messagingSenderId: '990427757093',
    projectId: 'restfoodblindbox',
    storageBucket: 'restfoodblindbox.firebasestorage.app',
    androidClientId: '990427757093-3slin5p8ef17ub41tiq5vlqi6dbej0f1.apps.googleusercontent.com',
    iosClientId: '990427757093-d499tfgpsgmj8huno8plirm7rns6q5v2.apps.googleusercontent.com',
    iosBundleId: 'com.kuanxing.co.restfoodblindbox',
  );

}